spring:
  application:
    name: userservice

  profiles:
    active: docker

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
      show-details: never
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true

logging:
  structured:
    json:
      enabled: true
