spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/userservicedb
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

jwt:
  secret-key: ${JWT_SECRET:KZSHyaAUVhrpWoTlO7DkzqozsZBt62dxRNYPm53iRzA}
